export enum Category {
  FRUIT = 'FRUIT',
  VEGETABLE = 'VEGETABLE',
  CANNED = 'CANNED',
  DAIRY = 'DAIRY',
  MEAT = 'MEAT',
  SEAFOOD = 'SEAFOOD',
  BAKERY = 'BAKERY',
  BEVERAGE = 'BEVERAGE',
  SNACK = 'SNACK',
  FROZEN = 'FROZEN',
}
